import type { Metadata } from "next";

import "./globals.css";
import "the-new-css-reset/css/reset.css";


import { Providers } from "./providers";



export const metadata: Metadata = {
  title: "Sport App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={roboto.className}> */}
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
